### ISSUE TITLE
homebridge chrashed when command arrive

### ISSUE THREAD

**Issue by meme1981** [vvpossible/homebridge_yeelight#45]
hi!
i have a problem:
homebridge crashes after connection if you touch anything in homekit or directly on the lamp

[2018-2-2 10:02:36] [yeelight] DidFinishLaunching
[2018-2-2 10:02:36] Homebridge is running on port 51823.
add to multicast group
listen on 0.0.0.0
no did or loc found!
stop this round of scan
start new round of scan
found Yeelight Bedside lamp: f8:24:41:ea:0c:d9
[2018-2-2 10:02:54] [yeelight] cached accessory: f8:24:41:ea:0c:d9
connect ok: f8:24:41:ea:0c:d9
discovered services
ble notification on
[2018-2-2 10:02:55] [yeelight] accesseory reachable
[2018-2-2 10:02:55] [yeelight] dev connected f8:24:41:ea:0c:d9 true
receive notify for did: f8:24:41:ea:0c:d9
stop this round of scan
stop discovering
receive notify for did: f8:24:41:ea:0c:d9
/usr/local/lib/node_modules/homebridge-yeelight/lib/yee.js:552
                dev.propChangeCb(dev, 'power', 0);
                    ^

TypeError: dev.propChangeCb is not a function
    at exports.YeeAgent.<anonymous> (/usr/local/lib/node_modules/homebridge-yeelight/lib/yee.js:552:21)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-yeelight/lib/yee.js:506:43)
    at emitTwo (events.js:125:13)
    at Characteristic.emit (events.js:213:7)
    at Noble.onRead (/usr/local/lib/node_modules/noble/lib/noble.js:312:20)
    at emitMany (events.js:146:13)
    at NobleBindings.emit (events.js:223:7)
    at NobleBindings.onNotification (/usr/local/lib/node_modules/noble/lib/hci-socket/bindings.js:413:8)
    at emitMany (events.js:146:13)
    at Gatt.emit (events.js:223:7)

**Comment by bassrock** [comment]
I am getting the same issue.

**Comment by Marcocanc** [comment]
+1
