### ISSUE TITLE
Issue with BLE bed side lights

### ISSUE THREAD

**Issue by davidbutler62** [vvpossible/homebridge_yeelight#57]
I have 2 BLE bedside side lights and they were working great.

I have noticed they are causing homebridge to restart now when i access them from the home app

Log message here:

May 14 18:28:23 homebridge homebridge[18146]: /usr/lib/node_modules/homebridge-yeelight/lib/yee.js:552
May 14 18:28:23 homebridge homebridge[18146]:                 dev.propChangeCb(dev, 'power', 0);
May 14 18:28:23 homebridge homebridge[18146]:                     ^
May 14 18:28:23 homebridge homebridge[18146]: TypeError: dev.propChangeCb is not a function
May 14 18:28:23 homebridge homebridge[18146]:     at exports.YeeAgent.<anonymous> (/usr/lib/node_modules/homebridge-yeelight/lib/yee.js:552:21)
May 14 18:28:23 homebridge homebridge[18146]:     at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge-yeelight/lib/yee.js:506:43)
May 14 18:28:23 homebridge homebridge[18146]:     at emitTwo (events.js:106:13)
May 14 18:28:23 homebridge homebridge[18146]:     at Characteristic.emit (events.js:194:7)
May 14 18:28:23 homebridge homebridge[18146]:     at Noble.onRead (/usr/lib/node_modules/noble/lib/noble.js:316:20)
May 14 18:28:23 homebridge homebridge[18146]:     at emitMany (events.js:127:13)
May 14 18:28:23 homebridge homebridge[18146]:     at NobleBindings.emit (events.js:204:7)
May 14 18:28:23 homebridge homebridge[18146]:     at NobleBindings.onNotification (/usr/lib/node_modules/noble/lib/hci-socket/bindings.js:413:8)
May 14 18:28:23 homebridge homebridge[18146]:     at emitMany (events.js:127:13)
May 14 18:28:23 homebridge homebridge[18146]:     at Gatt.emit (events.js:204:7)
May 14 18:28:23 homebridge homebridge[18146]:     at Gatt.onAclStreamData (/usr/lib/node_modules/noble/lib/hci-socket/gatt.js:115:16)
May 14 18:28:23 homebridge homebridge[18146]:     at emitTwo (events.js:111:20)
May 14 18:28:23 homebridge homebridge[18146]:     at AclStream.emit (events.js:194:7)
May 14 18:28:23 homebridge homebridge[18146]:     at AclStream.push (/usr/lib/node_modules/noble/lib/hci-socket/acl-stream.js:35:10)
May 14 18:28:23 homebridge homebridge[18146]:     at NobleBindings.onAclDataPkt (/usr/lib/node_modules/noble/lib/hci-socket/bindings.js:286:15)
May 14 18:28:23 homebridge homebridge[18146]:     at emitThree (events.js:116:13)
May 14 18:28:23 homebridge systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
May 14 18:28:23 homebridge systemd[1]: homebridge.service: Unit entered failed state.
May 14 18:28:23 homebridge systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 14 18:28:33 homebridge systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 14 18:28:33 homebridge systemd[1]: Stopped Node.js HomeKit Server.

Any ideas?  I did add a Yeelight desk lamp recently and also updated Homebridge-Yeelight, but i can't remember what the old version was :/

**Comment by davidbutler62** [comment]
Is it related to this also?  Bedside Lamp: Add Color Temperature support, Fix #45, Read CT and Color updates #55

**Comment by Marcocanc** [comment]
@davidbutler62 Yes, my PR should fix this!

**Comment by davidbutler62** [comment]
@Marcocanc How can I install the new version with the fix?  I already have 0.0.18 installed

**Comment by davidbutler62** [comment]
I tried, but the installation did not work

sudo npm install -g https://github.com/vvpossible/homebridge_yeelight/tarball/master

npm ERR! Linux 4.9.41-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "https://github.com/vvpossible/homebridge_yeelight/tarball/master"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-06-09T06_59_39_645Z-debug.log

**Comment by andreifinski** [comment]
@Marcocanc/@davidbutler62 , I am having the same issue, can you please help?

**Comment by Marcocanc** [comment]
Easiest fix would be for @vvpossible to tag a new version on npm

**Comment by davidbutler62** [comment]
I have gone back to 0.0.16 which seems not to crash when accessing the BLE bed side lights

**Comment by andreifinski** [comment]
Launched with 0.0.16 - nice more or less, though conversion from HSV to RGB doesn't really work which makes color change non-working as well. I think it was fixed in the upcoming versions though

**Comment by juanillo62gm** [comment]
Have you tested with last version (0.0.21) ?

**Comment by netRunner0** [comment]
yeelight atmosphere lamp homekit
Support?
